version: '3'

services:

  #stt_works:
  #  build:
  #    context: ./app
  #    dockerfile: dockerfiles/dockerfile.golang
  #  ports:
  #    - "8003:8080"
  #
  #  networks:
  #    - consultant_ai

    
  # stt:
  #  build: 
  #    context: ./app
  #    dockerfile: dockerfiles/dockerfile.python
  #  ports:
    #  - "8002:8000"
    #   networks:
    #   - consultant_ai
      

  minio:
    container_name: minio
    image: 'bitnami/minio:latest'
    volumes:
      - 'minio_data:/data'
    ports:
      - "7777:9000"
      - "9001:9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "aslon"
      MINIO_ROOT_PASSWORD: "aslon1213"
      MINIO_USE_SSL: "false"
      # MINIO_DEFAULT_BUCKETS: ""
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:

networks:
  consultant_ai:
    external: true
