# Stage 1: Build
FROM golang:1.22 
# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application source code
COPY . .
# Download dependencies
RUN go mod download

# Build the Go application
RUN go build -o /app/app/main .

# Command to run the application
CMD ["./main"]
